var mongoose = require('../db.js');

var clusterHistorySchema = mongoose.Schema({
  tick: Number,
  hour: Number,
  timestamp: Date,
  x: Number,
  active: Boolean,
  age: Number,
  size: Number,
  score: Number,
  value: Number,
  xp: Number,
  members: Number,
  ratio: Number,
  size_rank: Number,
  score_rank: Number,
  value_rank: Number,
  xp_rank: Number,
  size_growth: Number,
  score_growth: Number,
  value_growth: Number,
  xp_growth: Number,
  member_growth: Number,
  size_growth_pc: Number,
  score_growth_pc: Number,
  value_growth_pc: Number,
  xp_growth_pc: Number,
  size_rank_change: Number,
  score_rank_change: Number,
  value_rank_change: Number,
  xp_rank_change: Number,
  totalroundroids: Number,
  totallostroids: Number,
  totalroundroids_rank: Number,
  totallostroids_rank: Number,
  totalroundroids_rank_change: Number,
  totallostroids_rank_change: Number,
  totalroundroids_growth: Number,
  totallostroids_growth: Number,
  totalroundroids_growth_pc: Number,
  totallostroids_growth_pc: Number,
  ticksroiding: Number,
  ticksroided: Number,
  tickroids: Number,
  avroids: Number,
  roidxp: Number,
  vdiff: Number,
  sdiff: Number,
  xdiff: Number,
  rdiff: Number,
  mdiff: Number,
  vrankdiff: Number,
  srankdiff: Number,
  xrankdiff: Number,
  rrankdiff: Number,
  idle: Number,
  size_highest_rank: Number,
  size_highest_rank_tick: Number,
  size_lowest_rank: Number,
  size_lowest_rank_tick: Number,
  score_highest_rank: Number,
  score_highest_rank_tick: Number,
  score_lowest_rank: Number,
  score_lowest_rank_tick: Number,
  value_highest_rank: Number,
  value_highest_rank_tick: Number,
  value_lowest_rank: Number,
  value_lowest_rank_tick: Number,
  xp_highest_rank: Number,
  xp_highest_rank_tick: Number,
  xp_lowest_rank: Number,
  xp_lowest_rank_tick: Number
});

module.exports = mongoose.model('ClusterHistory', clusterHistorySchema, 'ClusterHistories');

